services:
  - type: web
    name: animal-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2" 
